name: fraud
channels:
  - conda-forge
dependencies:
  - python=3.11.12
  - pip
  - pip:
      - albumentations==2.0.8
      - efficientnet_pytorch==0.6.3
      - google-cloud-vision==3.10.1
      - matplotlib==3.10.7
      - mmcv==2.1.0
      - mmengine==0.10.7
      - mmsegmentation==1.2.2
      - natten==0.14.6
      - numpy==2.2.6
      - opencv-python==4.11.0.86
      - pandas==2.2.3
      - pdf2image==1.17.0
      - pillow==11.2.1
      - protobuf==5.29.4
      - pytorch-lightning==2.6.0
      - pyyaml==6.0.2
      - sconf==0.2.5
      - scikit-image==0.25.2
      - segmentation-models-pytorch==0.2.1
      - timm==0.4.12
      - torch==2.7.0+cu128
      - torchvision==0.22.0+cu128
      - tqdm==4.65.2
      - transformers==4.52.4
      - yacs==0.1.8
