model_name: "psccnet"
seed: 2025
result_path: "./result"
pretrained_model_name_or_path: "" # add weights here
dataset_name_or_path: [] # format: [["/path/to/images","/path/to/masks"], ...] or ["/path/to/images","/path/to/masks"]
train_batch_size: 8
input_size: [512,512]
lr: 2e-5
warmup_steps: 750
scheduler_num_training_samples_per_cycle_and_epoch: -1
max_epochs: 20
num_workers: 16
gradient_clip_val: 1.0
data_aug_config:
  enabled: true
  prob_disable: 0.5
  probs:
    spatial: 0.25
    visual: 0.16
    flip: 0.05
  compression:
    max_num: 3
    quality_range: [75, 100]
precision : "bf16-mixed"
accumulate_grad_batches : 1
check_point_every_n_step : True
steps_per_checkpoint: 1000
compile_model: True
loss_pos_weight: 4.0
class_coef: 0.1
persistent_workers: True
finetuning: True

